apiVersion: v1
kind: Service
metadata:
  name: springboot-playground-service
  labels:
    app: springboot-playground
spec:
  type: LoadBalancer
  selector:
    app: springboot-playground
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
